version: '3.8'

services:
  client:
    build: ./client
    container_name: client_container
    ports:
      - "80:80"

  gamefication-service:
    build: ./GameficationService
    container_name: gamefication-service_container
    ports:
      - "8001:8001"

  notification-service:
    build: ./NotificationService
    container_name: notification-service_container
    ports:
      - "8002:8002"

  playlists-catalog-service:
    build: ./PlaylistsCatalogService
    container_name: playlists-catalog-service_container
    ports:
      - "8003:8003"

  recommendation-service:
    build: ./RecommendationService
    container_name: recommendation-service_container
    ports:
      - "8004:8004"

  report-and-progress-service:
    build: ./ReportAndProgressService
    container_name: report-and-progress-service_container
    ports:
      - "8005:8005"

  training-service:
    build: ./TrainingService
    container_name: training-service_container
    ports:
      - "8006:8006"  

  user-management-service:
    build: ./UserManagementService
    container_name: user-management-service_container
    ports:
      - "8007:8007"