name: Gamification Service CI

on:
  push:
    branches:
      - main
    paths:
      - 'gamefication-service/**'

jobs:
  deploy-training-service:
    uses: ./.github/workflows/deploy-docker.yml
    with:
      service-dir: gamefication-service
      docker-hub-repo: leandrocrsfiap/gamefication-service
    secrets:
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}