name: Gamification Service CI

on:
  push:
    paths:
      - 'GamificationService/**'
  pull_request:
    paths:
      - 'GamificationService/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run build
        run: |
          echo "GamificationService building"