name: Notification Service CI

on:
  push:
    branches:
      - main
    paths:
      - 'notification-service/**'

jobs:
  deploy-training-service:
    uses: ./.github/workflows/deploy-docker.yml
    with:
      service-dir: notification-service
      docker-hub-repo: leandrocrsfiap/notification-service
    secrets:
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}