name: Playlists Catalog Service CI

on:
  push:
    branches:
      - main
    paths:
      - 'playlist-catalog-service/**'

jobs:
  deploy-training-service:
    uses: ./.github/workflows/deploy-docker.yml
    with:
      service-dir: playlist-catalog-service
      docker-hub-repo: leandrocrsfiap/playlists-catalog-service
    secrets:
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}