name: Playlists Catalog Service CI

on:
  push:
    paths:
      - 'PlaylistsCatalogService/**'
  pull_request:
    paths:
      - 'PlaylistsCatalogService/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run Payment API build
        run: |
          echo "PlaylistsCatalogService building"