name: Recommendation Service CI

on:
  push:
    branches:
      - main
    paths:
      - 'recommendation-worker/**'

jobs:
  deploy-training-service:
    uses: ./.github/workflows/deploy-docker.yml
    with:
      service-dir: recommendation-worker
      docker-hub-repo: leandrocrsfiap/recommendation-worker
    secrets:
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}