name: Report And Progress Service CI

on:
  push:
    branches:
      - main
    paths:
      - 'report-and-progress-service/**'

jobs:
  deploy-training-service:
    uses: ./.github/workflows/deploy-docker.yml
    with:
      service-dir:  report-and-progress-service
      docker-hub-repo: leandrocrsfiap/report-and-progress-service
    secrets:
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}