name: Training Service CI

on:
  push:
    branch:
      - main
    paths:
      - 'training-service/**'

jobs:
  deploy-training-service:
    uses: ./.github/workflows/deploy-docker.yml
    with:
      service-dir: training-service
      docker-hub-repo: leandrocrsfiap/training-service
    secrets:
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}