name: Training Service CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
  push:
    branch:
      - main
    paths:
      - 'TrainingService/**'

jobs:
  deploy-training-service:
    uses: .github/workflows/deploy-docker.yml@ci-cd
    with:
      service-name: training-service
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}