name: User Management Service CI

on:
  push:
    branch:
      - main
    paths:
      - 'user-management-service/**'

jobs:
  deploy-training-service:
    uses: ./.github/workflows/deploy-docker.yml
    with:
      service-dir: user-management-service
      docker-hub-repo: leandrocrsfiap/user-management-service
    secrets:
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}