name: User Management Service CI

on:
  push:
    paths:
      - 'UserManagementService/**'
  pull_request:
    paths:
      - 'UserManagementService/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run build
        run: |
          echo "UserManagementService building"